# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ergo < Formula
  desc "Multi-repo VS Code workspace manager"
  homepage "https://github.com/juan7732/ergo"
  version "0.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juan7732/ergo/releases/download/v0.1.0/ergo_0.1.0_darwin_amd64.tar.gz"
      sha256 "5c57e8acbcdb911334e06b06e1a9c098fb5093b13ed66e0e9ee59245c0721026"

      define_method(:install) do
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juan7732/ergo/releases/download/v0.1.0/ergo_0.1.0_darwin_arm64.tar.gz"
      sha256 "3ec7d7a142a1c5f9da889a15c133509a33abc44ce6141b7c3a45379a68aed932"

      define_method(:install) do
        bin.install "ergo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/juan7732/ergo/releases/download/v0.1.0/ergo_0.1.0_linux_amd64.tar.gz"
      sha256 "86100f75393b459b8794a8b27f8e0ba6765abea0ba20a1a82cbe8a97edee3741"
      define_method(:install) do
        bin.install "ergo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juan7732/ergo/releases/download/v0.1.0/ergo_0.1.0_linux_arm64.tar.gz"
      sha256 "f061ef4946584b31439388b6ce0b959abb1356122601c9e8ccfa370e2d0ff698"
      define_method(:install) do
        bin.install "ergo"
      end
    end
  end

  def caveats
    <<~EOS
      ergo shells out to a few tools for specific commands:
        • gh   (GitHub CLI) — required by `ergo update`
        • code (VS Code CLI) — required by `ergo open` and `ergo edit`
      Install them if you use those commands:
        brew install gh
        # VS Code: enable the `code` command via "Shell Command: Install 'code' command in PATH"
    EOS
  end

  test do
    system "#{bin}/ergo", "--version"
  end
end
